/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/muon_close_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag muon_close_real_len --resource parallel
/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/muon_far_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag muon_far_real_len --resource parallel
/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/proton_close_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag proton_close_real_len --resource parallel
/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/proton_far_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag proton_far_real_len --resource parallel



/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ele_close_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag ele_close_real_len --resource parallel
/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ele_far_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag ele_far_real_len --resource parallel
/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/gamma_close_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag gamma_close_real_len --resource parallel
/t2k/users/suvorov/dev/t2k-nd280-upgrade/submit/Reconstruction/submit_nd280upgrade_targetreco --inputfile /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/gamma_far_real --job-dir /t2k/users/suvorov/AnalysisResults/ndUP/SuperFGD/tracking/ --softw-dir /t2k/users/suvorov/dev/t2k-nd280-upgrade/ --nruns 200 --nexpts 1000 --cut-truth-fv 0  --debug 0 --debug-plot 0 --tag gamma_far_real_len --resource parallel


