/* Version information autogenerated by version fragment */
#ifndef ndupEvent_NAME
#define ndupEvent_NAME "ndupEvent"
#define ndupEvent_VERSION "v0r0"
#define ndupEvent_MAJOR_VERSION 0
#define ndupEvent_MINOR_VERSION 0
#define ndupEvent_PATCH_VERSION 0
#define BEFORE_ndupEvent(v,r,p) ((ndupEvent_MAJOR_VERSION==(v)&&ndupEvent_MINOR_VERSION==(r)&&ndupEvent_PATCH_VERSION<(p))||(ndupEvent_MAJOR_VERSION==(v)&&ndupEvent_MINOR_VERSION<(r))||(ndupEvent_MAJOR_VERSION<(v)))
#define EQUALS_ndupEvent(v,r,p) (ndupEvent_MAJOR_VERSION==(v)&&ndupEvent_MINOR_VERSION==(r)&&ndupEvent_PATCH_VERSION==(p))
#define ndupEvent_COMPILE_DATE "Sun Sep 11 17:09:44 UTC 2016"
#define ndupEvent_COMPILE_HOST "localhost.localdomain"
#define ndupEvent_COMPILE_UNAME "Linux localhost.localdomain 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 20:37:17 CST 2013 x86_64 x86_64 x86_64 GNU/Linux"
#define ndupEvent_COMPILE_DIR "/home/evrazhka/ND280/nd280rep/v11r31/highlandUP/ndupEvent/v0r0/cmt"
#endif
