# Macro file for the initialization phase of "exampleN02.cc"
# when runing in interactive mode

# Sets some default verbose
/control/verbose 1
#/run/verbose 1
#/tracking/verbose 2 # print many physics informations about each step (daughters,...)

# Set the physics list
#/physlist/usePAIModel true
#/physlist/setHadronicPhysList QGSP_BERT

# Particle Max Step Size 
/testem/stepMax 1.0 mm

# Set the magnetic field
/field/setStepperType 4
/field/setMinStep 0.1 mm
/field/setField 0.2 0 0 tesla
/field/update



### NEW
# Set nd280mc visible detectors 
#/t2k/Basket/DsECal/visible 1
#/t2k/Basket/DsECal/visibleDaughters 1
#/t2k/Basket/DsECal/Module/Active/ScintHoriz/Bar/visible 1
#/t2k/Basket/DsECal/Module/Active/ScintHoriz/Bar/visibleDaughters 1
#/t2k/Basket/DsECal/Module/Active/ScintHoriz/visible 1
#/t2k/Basket/DsECal/Module/Active/ScintHoriz/visibleDaughters 1
#/t2k/Basket/DsECal/Module/Active/ScintVert/Bar/visible 1
#/t2k/Basket/DsECal/Module/Active/ScintVert/Bar/visibleDaughters 1
#/t2k/Basket/DsECal/Module/Active/ScintVert/visible 1
#/t2k/Basket/DsECal/Module/Active/ScintVert/visibleDaughters 1
####



# Set geometry
#/N02/det/setTargetMate1 WAGASHIScintEmpty #FGDScintillator
#/N02/det/setTargetMate2 Water #ActiveWater

# Test geometry (overlaps...)	
/geometry/test/run
#/geometry/test/verbosity 1
#/geometry/test/tolerance 1000 mm

# Set the particle generator: "Generator" (NEUT or GENIE is not specified here) or "ParticleGun"
/generator/type Generator
#/generator/type ParticleGun
		
# Set the particle gun 
/gun/particle mu-
/gun/energy 600 MeV  # kinetic energy
/gun/direction 0 0 1 # momentum direction
#/gun/position 0 0 0 mm  # starting position		
#/gun/position 0 0 2500 mm  # starting position
/gun/position -500 -500 2500 mm  # starting position
/gun/number   1      # number of particles


/vis/disable