//
// File generated by /home/evrazhka/ND280/nd280rep/v11r31/ROOT/v5r34p09n04/amd64_linux26/bin/rootcint at Thu Mar 30 01:08:20 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIdictdIConfigTreeTools_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ConfigTreeTools_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::ConfigTreeTools ConfigTreeTools;
      #else
      class ConfigTreeTools  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~ConfigTreeTools() throw() {};
         ::SystematicManager* _syst; //
         ::ConfigurationManager* _conf; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ConfigTreeTools_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void ConfigTreeTools_Dictionary();
   static void *new_ConfigTreeTools(void *p = 0);
   static void *newArray_ConfigTreeTools(Long_t size, void *p);
   static void delete_ConfigTreeTools(void *p);
   static void deleteArray_ConfigTreeTools(void *p);
   static void destruct_ConfigTreeTools(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ConfigTreeTools*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::ConfigTreeTools) == sizeof(::ROOT::Shadow::ConfigTreeTools));
      ::ConfigTreeTools *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::ConfigTreeTools),0);
      static ::ROOT::TGenericClassInfo 
         instance("ConfigTreeTools", "./../src/ConfigTreeTools.hxx", 9,
                  typeid(::ConfigTreeTools), DefineBehavior(ptr, ptr),
                  &ConfigTreeTools_ShowMembers, &ConfigTreeTools_Dictionary, isa_proxy, 4,
                  sizeof(::ConfigTreeTools) );
      instance.SetNew(&new_ConfigTreeTools);
      instance.SetNewArray(&newArray_ConfigTreeTools);
      instance.SetDelete(&delete_ConfigTreeTools);
      instance.SetDeleteArray(&deleteArray_ConfigTreeTools);
      instance.SetDestructor(&destruct_ConfigTreeTools);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ConfigTreeTools*)
   {
      return GenerateInitInstanceLocal((::ConfigTreeTools*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ConfigTreeTools*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void ConfigTreeTools_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::ConfigTreeTools*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void ConfigTreeTools_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class ConfigTreeTools.
      typedef ::ROOT::Shadow::ConfigTreeTools ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::ConfigTreeTools*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_syst", &sobj->_syst);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_conf", &sobj->_conf);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ConfigTreeTools(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ConfigTreeTools : new ::ConfigTreeTools;
   }
   static void *newArray_ConfigTreeTools(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ConfigTreeTools[nElements] : new ::ConfigTreeTools[nElements];
   }
   // Wrapper around operator delete
   static void delete_ConfigTreeTools(void *p) {
      delete ((::ConfigTreeTools*)p);
   }
   static void deleteArray_ConfigTreeTools(void *p) {
      delete [] ((::ConfigTreeTools*)p);
   }
   static void destruct_ConfigTreeTools(void *p) {
      typedef ::ConfigTreeTools current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ConfigTreeTools

/********************************************************
* ../dict/ConfigTreeTools_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableConfigTreeTools_Dict();

extern "C" void G__set_cpp_environmentConfigTreeTools_Dict() {
  G__cpp_reset_tagtableConfigTreeTools_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevConfigTreeTools_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ConfigTreeTools */
static int G__ConfigTreeTools_Dict_756_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ConfigTreeTools* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ConfigTreeTools[n];
     } else {
       p = new((void*) gvp) ConfigTreeTools[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ConfigTreeTools;
     } else {
       p = new((void*) gvp) ConfigTreeTools;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ConfigTreeTools_Dict_756_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ConfigTreeTools* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new ConfigTreeTools(*(SystematicManager*) libp->para[0].ref, *(ConfigurationManager*) libp->para[1].ref);
   } else {
     p = new((void*) gvp) ConfigTreeTools(*(SystematicManager*) libp->para[0].ref, *(ConfigurationManager*) libp->para[1].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ConfigTreeTools_Dict_756_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ConfigTreeTools*) G__getstructoffset())->Initialize(*(SystematicManager*) libp->para[0].ref, *(ConfigurationManager*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ConfigTreeTools_Dict_756_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const ConfigTreeTools*) G__getstructoffset())->GetWeightIndex(*(string*) libp->para[0].ref, *(string*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ConfigTreeTools_Dict_756_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const ConfigTreeTools*) G__getstructoffset())->GetWeightIndex((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ConfigTreeTools_Dict_756_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ConfigTreeTools* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ConfigTreeTools(*(ConfigTreeTools*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ConfigTreeTools G__TConfigTreeTools;
static int G__ConfigTreeTools_Dict_756_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ConfigTreeTools*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ConfigTreeTools*) (soff+(sizeof(ConfigTreeTools)*i)))->~G__TConfigTreeTools();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ConfigTreeTools*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ConfigTreeTools*) (soff))->~G__TConfigTreeTools();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ConfigTreeTools_Dict_756_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ConfigTreeTools* dest = (ConfigTreeTools*) G__getstructoffset();
   *dest = *(ConfigTreeTools*) libp->para[0].ref;
   const ConfigTreeTools& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ConfigTreeTools */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncConfigTreeTools_Dict {
 public:
  G__Sizep2memfuncConfigTreeTools_Dict(): p(&G__Sizep2memfuncConfigTreeTools_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncConfigTreeTools_Dict::*p)();
};

size_t G__get_sizep2memfuncConfigTreeTools_Dict()
{
  G__Sizep2memfuncConfigTreeTools_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceConfigTreeTools_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableConfigTreeTools_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaBunchC*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<StepBase*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEStepBasemUcOallocatorlEStepBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEStepBasemUcOallocatorlEStepBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<UInt_t> >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<UInt_t> >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<unsigned int,allocator<unsigned int> > >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<AnaRecObjectC*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_setlEAnaRecObjectCmUcOlesslEAnaRecObjectCmUgRcOallocatorlEAnaRecObjectCmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<AnaRecObjectC*,less<AnaRecObjectC*> >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_setlEAnaRecObjectCmUcOlesslEAnaRecObjectCmUgRcOallocatorlEAnaRecObjectCmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("less<std::string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_lesslEstringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("less<string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_lesslEstringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string,std::less<std::string> >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string,std::less<string> >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<string>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixT<double>*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<indexlink>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEindexlinkcOallocatorlEindexlinkgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEindexlinkcOallocatorlEindexlinkgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEindexlinkcOallocatorlEindexlinkgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEindexlinkcOallocatorlEindexlinkgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEindexlinkcOallocatorlEindexlinkgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<covlink>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEcovlinkcOallocatorlEcovlinkgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEcovlinkcOallocatorlEcovlinkgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEcovlinkcOallocatorlEcovlinkgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEcovlinkcOallocatorlEcovlinkgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEcovlinkcOallocatorlEcovlinkgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SelectionBase*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SystematicBase*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ToyExperiment*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ToyVariationWrite>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ConfigurationBase*>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_vectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ConfigTreeTools */
static void G__setup_memvarConfigTreeTools(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools));
   { ConfigTreeTools *p; p=(ConfigTreeTools*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_SystematicManager),-1,-1,2,"_syst=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigurationManager),-1,-1,2,"_conf=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarConfigTreeTools_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncConfigTreeTools(void) {
   /* ConfigTreeTools */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools));
   G__memfunc_setup("ConfigTreeTools",1527,G__ConfigTreeTools_Dict_756_0_1, 105, G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ConfigTreeTools",1527,G__ConfigTreeTools_Dict_756_0_2, 105, G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools), -1, 0, 2, 1, 1, 0, 
"u 'SystematicManager' - 1 - syst u 'ConfigurationManager' - 1 - conf", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__ConfigTreeTools_Dict_756_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'SystematicManager' - 1 - syst u 'ConfigurationManager' - 1 - conf", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWeightIndex",1408,G__ConfigTreeTools_Dict_756_0_4, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 8, 
"u 'string' - 11 - conf u 'string' - 11 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWeightIndex",1408,G__ConfigTreeTools_Dict_756_0_5, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 8, 
"i - 'Int_t' 0 - conf i - 'Int_t' 0 - weight", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("ConfigTreeTools", 1527, G__ConfigTreeTools_Dict_756_0_6, (int) ('i'), G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools), -1, 0, 1, 1, 1, 0, "u 'ConfigTreeTools' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ConfigTreeTools", 1653, G__ConfigTreeTools_Dict_756_0_7, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ConfigTreeTools_Dict_756_0_8, (int) ('u'), G__get_linked_tagnum(&G__ConfigTreeTools_DictLN_ConfigTreeTools), -1, 1, 1, 1, 1, 0, "u 'ConfigTreeTools' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncConfigTreeTools_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalConfigTreeTools_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcConfigTreeTools_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR = { "vector<AnaBunchC*,allocator<AnaBunchC*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaBunchC*,allocator<AnaBunchC*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_lesslEstringgR = { "less<string>" , 115 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR = { "vector<StepBase*,allocator<StepBase*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEStepBasemUcOallocatorlEStepBasemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<StepBase*,allocator<StepBase*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR = { "vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR = { "set<string,less<string>,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_setlEAnaRecObjectCmUcOlesslEAnaRecObjectCmUgRcOallocatorlEAnaRecObjectCmUgRsPgR = { "set<AnaRecObjectC*,less<AnaRecObjectC*>,allocator<AnaRecObjectC*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_SystematicManager = { "SystematicManager" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgR = { "vector<TMatrixT<double>*,allocator<TMatrixT<double>*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixT<double>*,allocator<TMatrixT<double>*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEindexlinkcOallocatorlEindexlinkgRsPgR = { "vector<indexlink,allocator<indexlink> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEindexlinkcOallocatorlEindexlinkgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<indexlink,allocator<indexlink> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEcovlinkcOallocatorlEcovlinkgRsPgR = { "vector<covlink,allocator<covlink> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEcovlinkcOallocatorlEcovlinkgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<covlink,allocator<covlink> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgR = { "vector<SelectionBase*,allocator<SelectionBase*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SelectionBase*,allocator<SelectionBase*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgR = { "vector<SystematicBase*,allocator<SystematicBase*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SystematicBase*,allocator<SystematicBase*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgR = { "vector<ToyExperiment*,allocator<ToyExperiment*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ToyExperiment*,allocator<ToyExperiment*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgR = { "vector<ToyVariationWrite,allocator<ToyVariationWrite> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ToyVariationWrite,allocator<ToyVariationWrite> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_ConfigurationManager = { "ConfigurationManager" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_vectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgR = { "vector<ConfigurationBase*,allocator<ConfigurationBase*> >" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ConfigurationBase*,allocator<ConfigurationBase*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ConfigTreeTools_DictLN_ConfigTreeTools = { "ConfigTreeTools" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableConfigTreeTools_Dict() {
  G__ConfigTreeTools_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_string.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_lesslEstringgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEStepBasemUcOallocatorlEStepBasemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_setlEAnaRecObjectCmUcOlesslEAnaRecObjectCmUgRcOallocatorlEAnaRecObjectCmUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_SystematicManager.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEindexlinkcOallocatorlEindexlinkgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEindexlinkcOallocatorlEindexlinkgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEcovlinkcOallocatorlEcovlinkgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEcovlinkcOallocatorlEcovlinkgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_ConfigurationManager.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_vectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ConfigTreeTools_DictLN_ConfigTreeTools.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableConfigTreeTools_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_string);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_lesslEstringgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEStepBasemUcOallocatorlEStepBasemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_setlEAnaRecObjectCmUcOlesslEAnaRecObjectCmUgRcOallocatorlEAnaRecObjectCmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_SystematicManager);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRmUcOallocatorlETMatrixTlEdoublegRmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEindexlinkcOallocatorlEindexlinkgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEindexlinkcOallocatorlEindexlinkgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEcovlinkcOallocatorlEcovlinkgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEcovlinkcOallocatorlEcovlinkgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESelectionBasemUcOallocatorlESelectionBasemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlESystematicBasemUcOallocatorlESystematicBasemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyExperimentmUcOallocatorlEToyExperimentmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEToyVariationWritecOallocatorlEToyVariationWritegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_ConfigurationManager);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_vectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_reverse_iteratorlEvectorlEConfigurationBasemUcOallocatorlEConfigurationBasemUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ConfigTreeTools_DictLN_ConfigTreeTools),sizeof(ConfigTreeTools),-1,296192,(char*)NULL,G__setup_memvarConfigTreeTools,G__setup_memfuncConfigTreeTools);
}
extern "C" void G__cpp_setupConfigTreeTools_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupConfigTreeTools_Dict()");
  G__set_cpp_environmentConfigTreeTools_Dict();
  G__cpp_setup_tagtableConfigTreeTools_Dict();

  G__cpp_setup_inheritanceConfigTreeTools_Dict();

  G__cpp_setup_typetableConfigTreeTools_Dict();

  G__cpp_setup_memvarConfigTreeTools_Dict();

  G__cpp_setup_memfuncConfigTreeTools_Dict();
  G__cpp_setup_globalConfigTreeTools_Dict();
  G__cpp_setup_funcConfigTreeTools_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncConfigTreeTools_Dict();
  return;
}
class G__cpp_setup_initConfigTreeTools_Dict {
  public:
    G__cpp_setup_initConfigTreeTools_Dict() { G__add_setup_func("ConfigTreeTools_Dict",(G__incsetup)(&G__cpp_setupConfigTreeTools_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initConfigTreeTools_Dict() { G__remove_setup_func("ConfigTreeTools_Dict"); }
};
G__cpp_setup_initConfigTreeTools_Dict G__cpp_setup_initializerConfigTreeTools_Dict;

