/********************************************************************
* ../dict/HistoStack_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/HistoStack_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHistoStack_Dict();
extern void G__cpp_setup_inheritanceHistoStack_Dict();
extern void G__cpp_setup_typetableHistoStack_Dict();
extern void G__cpp_setup_memvarHistoStack_Dict();
extern void G__cpp_setup_globalHistoStack_Dict();
extern void G__cpp_setup_memfuncHistoStack_Dict();
extern void G__cpp_setup_funcHistoStack_Dict();
extern void G__set_cpp_environmentHistoStack_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/HistoStack.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HistoStack_DictLN_string;
extern G__linked_taginfo G__HistoStack_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistoStack_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistoStack_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HistoStack_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HistoStack_DictLN_TH1F;
extern G__linked_taginfo G__HistoStack_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__HistoStack_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__HistoStack_DictLN_TH2F;
extern G__linked_taginfo G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HistoStack_DictLN_THStack;
extern G__linked_taginfo G__HistoStack_DictLN_TLegend;
extern G__linked_taginfo G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__HistoStack_DictLN_HistoStack;
extern G__linked_taginfo G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR;
extern G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR;

/* STUB derived class for protected member access */
