//
// File generated by /home/evrazhka/ND280/nd280rep/v11r31/ROOT/v5r34p09n04/amd64_linux26/bin/rootcint at Tue Aug 23 15:24:29 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIdictdIHistoStack_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "HistoStack_Dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::HistoStack HistoStack;
      #else
      class HistoStack  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~HistoStack() throw() {};
         vector< ::TH1F* > _histos1D; //
         vector< ::TH1F* > _histos1D_draw; //
         vector< ::TH2F* > _histos2D; //
         ::THStack* _stack; //
         ::TH1F* _hall1D; //
         ::TH1F* _hall1D_stat; //
         ::TH1F* _hall1D_syst; //
         ::TH1F* _hall1D_draw; //
         ::TH2F* _hall2D; //
         string _title; //
         string _titleX; //
         string _titleY; //
         bool _is1D; //
         bool _is2D; //
         vector< ::string > _systHistosGroups; //
         string _currentSystGroup; //
         map< ::string, ::TH2F* > _h1; //
         map< ::string, ::TH2F* > _h1w; //
         map< ::string, ::TH2F* > _h2; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void HistoStack_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void HistoStack_Dictionary();
   static void delete_HistoStack(void *p);
   static void deleteArray_HistoStack(void *p);
   static void destruct_HistoStack(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::HistoStack*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::HistoStack) == sizeof(::ROOT::Shadow::HistoStack));
      ::HistoStack *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::HistoStack),0);
      static ::ROOT::TGenericClassInfo 
         instance("HistoStack", "./../src/HistoStack.hxx", 25,
                  typeid(::HistoStack), DefineBehavior(ptr, ptr),
                  &HistoStack_ShowMembers, &HistoStack_Dictionary, isa_proxy, 4,
                  sizeof(::HistoStack) );
      instance.SetDelete(&delete_HistoStack);
      instance.SetDeleteArray(&deleteArray_HistoStack);
      instance.SetDestructor(&destruct_HistoStack);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::HistoStack*)
   {
      return GenerateInitInstanceLocal((::HistoStack*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::HistoStack*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void HistoStack_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::HistoStack*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void HistoStack_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class HistoStack.
      typedef ::ROOT::Shadow::HistoStack ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::HistoStack*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_histos1D", (void*)&sobj->_histos1D);
      R__insp.InspectMember("vector<TH1F*>", (void*)&sobj->_histos1D, "_histos1D.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_histos1D_draw", (void*)&sobj->_histos1D_draw);
      R__insp.InspectMember("vector<TH1F*>", (void*)&sobj->_histos1D_draw, "_histos1D_draw.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_histos2D", (void*)&sobj->_histos2D);
      R__insp.InspectMember("vector<TH2F*>", (void*)&sobj->_histos2D, "_histos2D.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_stack", &sobj->_stack);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_hall1D", &sobj->_hall1D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_hall1D_stat", &sobj->_hall1D_stat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_hall1D_syst", &sobj->_hall1D_syst);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_hall1D_draw", &sobj->_hall1D_draw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_hall2D", &sobj->_hall2D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_title", (void*)&sobj->_title);
      R__insp.InspectMember("string", (void*)&sobj->_title, "_title.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_titleX", (void*)&sobj->_titleX);
      R__insp.InspectMember("string", (void*)&sobj->_titleX, "_titleX.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_titleY", (void*)&sobj->_titleY);
      R__insp.InspectMember("string", (void*)&sobj->_titleY, "_titleY.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_is1D", &sobj->_is1D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_is2D", &sobj->_is2D);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_systHistosGroups", (void*)&sobj->_systHistosGroups);
      R__insp.InspectMember("vector<std::string>", (void*)&sobj->_systHistosGroups, "_systHistosGroups.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_currentSystGroup", (void*)&sobj->_currentSystGroup);
      R__insp.InspectMember("string", (void*)&sobj->_currentSystGroup, "_currentSystGroup.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_h1", (void*)&sobj->_h1);
      R__insp.InspectMember("map<std::string,TH2F*>", (void*)&sobj->_h1, "_h1.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_h1w", (void*)&sobj->_h1w);
      R__insp.InspectMember("map<std::string,TH2F*>", (void*)&sobj->_h1w, "_h1w.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_h2", (void*)&sobj->_h2);
      R__insp.InspectMember("map<std::string,TH2F*>", (void*)&sobj->_h2, "_h2.", false);
   }

}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_HistoStack(void *p) {
      delete ((::HistoStack*)p);
   }
   static void deleteArray_HistoStack(void *p) {
      delete [] ((::HistoStack*)p);
   }
   static void destruct_HistoStack(void *p) {
      typedef ::HistoStack current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::HistoStack

namespace ROOT {
   void maplEstringcOTH2FmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEstringcOTH2FmUgR_Dictionary();
   static void *new_maplEstringcOTH2FmUgR(void *p = 0);
   static void *newArray_maplEstringcOTH2FmUgR(Long_t size, void *p);
   static void delete_maplEstringcOTH2FmUgR(void *p);
   static void deleteArray_maplEstringcOTH2FmUgR(void *p);
   static void destruct_maplEstringcOTH2FmUgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<string,TH2F*>*)
   {
      map<string,TH2F*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,TH2F*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<string,TH2F*>", -2, "/home/evrazhka/ND280/nd280rep/v11r31/ROOT/v5r34p09n04/amd64_linux26/lib/root/cint/cint/lib/prec_stl/map", 63,
                  typeid(map<string,TH2F*>), DefineBehavior(ptr, ptr),
                  0, &maplEstringcOTH2FmUgR_Dictionary, isa_proxy, 0,
                  sizeof(map<string,TH2F*>) );
      instance.SetNew(&new_maplEstringcOTH2FmUgR);
      instance.SetNewArray(&newArray_maplEstringcOTH2FmUgR);
      instance.SetDelete(&delete_maplEstringcOTH2FmUgR);
      instance.SetDeleteArray(&deleteArray_maplEstringcOTH2FmUgR);
      instance.SetDestructor(&destruct_maplEstringcOTH2FmUgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,TH2F*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<string,TH2F*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEstringcOTH2FmUgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<string,TH2F*>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEstringcOTH2FmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,TH2F*> : new map<string,TH2F*>;
   }
   static void *newArray_maplEstringcOTH2FmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,TH2F*>[nElements] : new map<string,TH2F*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEstringcOTH2FmUgR(void *p) {
      delete ((map<string,TH2F*>*)p);
   }
   static void deleteArray_maplEstringcOTH2FmUgR(void *p) {
      delete [] ((map<string,TH2F*>*)p);
   }
   static void destruct_maplEstringcOTH2FmUgR(void *p) {
      typedef map<string,TH2F*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<string,TH2F*>

namespace ROOT {
   void vectorlETH1FmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlETH1FmUgR_Dictionary();
   static void *new_vectorlETH1FmUgR(void *p = 0);
   static void *newArray_vectorlETH1FmUgR(Long_t size, void *p);
   static void delete_vectorlETH1FmUgR(void *p);
   static void deleteArray_vectorlETH1FmUgR(void *p);
   static void destruct_vectorlETH1FmUgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<TH1F*>*)
   {
      vector<TH1F*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TH1F*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<TH1F*>", -2, "/home/evrazhka/ND280/nd280rep/v11r31/ROOT/v5r34p09n04/amd64_linux26/lib/root/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<TH1F*>), DefineBehavior(ptr, ptr),
                  0, &vectorlETH1FmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<TH1F*>) );
      instance.SetNew(&new_vectorlETH1FmUgR);
      instance.SetNewArray(&newArray_vectorlETH1FmUgR);
      instance.SetDelete(&delete_vectorlETH1FmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlETH1FmUgR);
      instance.SetDestructor(&destruct_vectorlETH1FmUgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TH1F*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<TH1F*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlETH1FmUgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<TH1F*>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlETH1FmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TH1F*> : new vector<TH1F*>;
   }
   static void *newArray_vectorlETH1FmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TH1F*>[nElements] : new vector<TH1F*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlETH1FmUgR(void *p) {
      delete ((vector<TH1F*>*)p);
   }
   static void deleteArray_vectorlETH1FmUgR(void *p) {
      delete [] ((vector<TH1F*>*)p);
   }
   static void destruct_vectorlETH1FmUgR(void *p) {
      typedef vector<TH1F*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<TH1F*>

namespace ROOT {
   void vectorlETH2FmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlETH2FmUgR_Dictionary();
   static void *new_vectorlETH2FmUgR(void *p = 0);
   static void *newArray_vectorlETH2FmUgR(Long_t size, void *p);
   static void delete_vectorlETH2FmUgR(void *p);
   static void deleteArray_vectorlETH2FmUgR(void *p);
   static void destruct_vectorlETH2FmUgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<TH2F*>*)
   {
      vector<TH2F*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TH2F*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<TH2F*>", -2, "/home/evrazhka/ND280/nd280rep/v11r31/ROOT/v5r34p09n04/amd64_linux26/lib/root/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<TH2F*>), DefineBehavior(ptr, ptr),
                  0, &vectorlETH2FmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<TH2F*>) );
      instance.SetNew(&new_vectorlETH2FmUgR);
      instance.SetNewArray(&newArray_vectorlETH2FmUgR);
      instance.SetDelete(&delete_vectorlETH2FmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlETH2FmUgR);
      instance.SetDestructor(&destruct_vectorlETH2FmUgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TH2F*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<TH2F*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlETH2FmUgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<TH2F*>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlETH2FmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TH2F*> : new vector<TH2F*>;
   }
   static void *newArray_vectorlETH2FmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TH2F*>[nElements] : new vector<TH2F*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlETH2FmUgR(void *p) {
      delete ((vector<TH2F*>*)p);
   }
   static void deleteArray_vectorlETH2FmUgR(void *p) {
      delete [] ((vector<TH2F*>*)p);
   }
   static void destruct_vectorlETH2FmUgR(void *p) {
      typedef vector<TH2F*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<TH2F*>

namespace ROOT {
   void vectorlEstringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEstringgR_Dictionary();
   static void *new_vectorlEstringgR(void *p = 0);
   static void *newArray_vectorlEstringgR(Long_t size, void *p);
   static void delete_vectorlEstringgR(void *p);
   static void deleteArray_vectorlEstringgR(void *p);
   static void destruct_vectorlEstringgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<string>*)
   {
      vector<string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<string>", -2, "/home/evrazhka/ND280/nd280rep/v11r31/ROOT/v5r34p09n04/amd64_linux26/lib/root/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<string>), DefineBehavior(ptr, ptr),
                  0, &vectorlEstringgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<string>) );
      instance.SetNew(&new_vectorlEstringgR);
      instance.SetNewArray(&newArray_vectorlEstringgR);
      instance.SetDelete(&delete_vectorlEstringgR);
      instance.SetDeleteArray(&deleteArray_vectorlEstringgR);
      instance.SetDestructor(&destruct_vectorlEstringgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEstringgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<string>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string> : new vector<string>;
   }
   static void *newArray_vectorlEstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string>[nElements] : new vector<string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEstringgR(void *p) {
      delete ((vector<string>*)p);
   }
   static void deleteArray_vectorlEstringgR(void *p) {
      delete [] ((vector<string>*)p);
   }
   static void destruct_vectorlEstringgR(void *p) {
      typedef vector<string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<string>

/********************************************************
* ../dict/HistoStack_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableHistoStack_Dict();

extern "C" void G__set_cpp_environmentHistoStack_Dict() {
  G__cpp_reset_tagtableHistoStack_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevHistoStack_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* HistoStack */
static int G__HistoStack_Dict_537_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   HistoStack* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new HistoStack(
*(string*) libp->para[0].ref, *(string*) libp->para[1].ref
, *(string*) libp->para[2].ref);
   } else {
     p = new((void*) gvp) HistoStack(
*(string*) libp->para[0].ref, *(string*) libp->para[1].ref
, *(string*) libp->para[2].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__HistoStack_DictLN_HistoStack));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((HistoStack*) G__getstructoffset())->Is1D());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((HistoStack*) G__getstructoffset())->Is2D());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->Add((TH1F*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), *(string*) libp->para[5].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((HistoStack*) G__getstructoffset())->Add((TH2F*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), *(string*) libp->para[3].ref);
      G__setnull(result7);
      break;
   case 3:
      ((HistoStack*) G__getstructoffset())->Add((TH2F*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 8:
      ((HistoStack*) G__getstructoffset())->Draw(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, *(string*) libp->para[4].ref, *(string*) libp->para[5].ref
, *(string*) libp->para[6].ref, (int) G__int(libp->para[7]));
      G__setnull(result7);
      break;
   case 7:
      ((HistoStack*) G__getstructoffset())->Draw(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, *(string*) libp->para[4].ref, *(string*) libp->para[5].ref
, *(string*) libp->para[6].ref);
      G__setnull(result7);
      break;
   case 6:
      ((HistoStack*) G__getstructoffset())->Draw((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, *(string*) libp->para[4].ref, *(string*) libp->para[5].ref);
      G__setnull(result7);
      break;
   case 5:
      ((HistoStack*) G__getstructoffset())->Draw((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, *(string*) libp->para[4].ref);
      G__setnull(result7);
      break;
   case 4:
      ((HistoStack*) G__getstructoffset())->Draw((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((HistoStack*) G__getstructoffset())->Draw(*(string*) libp->para[0].ref, *(string*) libp->para[1].ref);
      G__setnull(result7);
      break;
   case 1:
      ((HistoStack*) G__getstructoffset())->Draw(*(string*) libp->para[0].ref);
      G__setnull(result7);
      break;
   case 0:
      ((HistoStack*) G__getstructoffset())->Draw();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->SetTotal((TH1F*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->SetTotal((TH2F*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetTotal1D());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetTotalStat1D());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetTotalSyst1D());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetTotal2D());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((HistoStack*) G__getstructoffset())->AddTotal((TH1F*) G__int(libp->para[0]), (TH1F*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((HistoStack*) G__getstructoffset())->AddTotal((TH1F*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->AddSystHistos((TH2F*) G__int(libp->para[0]), (TH2F*) G__int(libp->para[1])
, (TH2F*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->GetSystHistos(*(string*) libp->para[0].ref, libp->para[1].ref ? *(TH2F**) libp->para[1].ref : *(TH2F**) (void*) (&G__Mlong(libp->para[1]))
, libp->para[2].ref ? *(TH2F**) libp->para[2].ref : *(TH2F**) (void*) (&G__Mlong(libp->para[2])), libp->para[3].ref ? *(TH2F**) libp->para[3].ref : *(TH2F**) (void*) (&G__Mlong(libp->para[3])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->AddSystHistosGroup(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->SetCurrentSystGroup(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((HistoStack*) G__getstructoffset())->GetCurrentSystGroup();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<std::string>* pobj;
         const vector<std::string> xobj = ((const HistoStack*) G__getstructoffset())->GetSystHistosGroups();
         pobj = new vector<std::string>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->AddTotal((TH2F*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->FillLegend((TLegend*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetHisto1D(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetHisto1D((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetHisto2D(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((HistoStack*) G__getstructoffset())->GetHisto2D((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const HistoStack*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((HistoStack*) G__getstructoffset())->NormalizeByArea(*(string*) libp->para[0].ref, (double) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((HistoStack*) G__getstructoffset())->NormalizeByArea(*(string*) libp->para[0].ref);
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->ResetDrawHistos();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((HistoStack*) G__getstructoffset())->GetMaximum(*(string*) libp->para[0].ref));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((HistoStack*) G__getstructoffset())->GetMaximum());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((HistoStack*) G__getstructoffset())->GetMaximumWithError(*(string*) libp->para[0].ref));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((HistoStack*) G__getstructoffset())->GetMaximumWithError());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->SetMaximum((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoStack_Dict_537_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((HistoStack*) G__getstructoffset())->SetMinimum((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__HistoStack_Dict_537_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   HistoStack* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new HistoStack(*(HistoStack*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__HistoStack_DictLN_HistoStack));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef HistoStack G__THistoStack;
static int G__HistoStack_Dict_537_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (HistoStack*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((HistoStack*) (soff+(sizeof(HistoStack)*i)))->~G__THistoStack();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (HistoStack*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((HistoStack*) (soff))->~G__THistoStack();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__HistoStack_Dict_537_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   HistoStack* dest = (HistoStack*) G__getstructoffset();
   *dest = *(HistoStack*) libp->para[0].ref;
   const HistoStack& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* HistoStack */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncHistoStack_Dict {
 public:
  G__Sizep2memfuncHistoStack_Dict(): p(&G__Sizep2memfuncHistoStack_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncHistoStack_Dict::*p)();
};

size_t G__get_sizep2memfuncHistoStack_Dict()
{
  G__Sizep2memfuncHistoStack_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceHistoStack_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableHistoStack_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1F*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2F*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TH2F*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2F*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2F*>",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH2F*,less<string> >",117,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* HistoStack */
static void G__setup_memvarHistoStack(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__HistoStack_DictLN_HistoStack));
   { HistoStack *p; p=(HistoStack*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR),G__defined_typename("vector<TH1F*>"),-1,2,"_histos1D=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR),G__defined_typename("vector<TH1F*>"),-1,2,"_histos1D_draw=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR),G__defined_typename("vector<TH2F*>"),-1,2,"_histos2D=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_THStack),-1,-1,2,"_stack=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F),-1,-1,2,"_hall1D=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F),-1,-1,2,"_hall1D_stat=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F),-1,-1,2,"_hall1D_syst=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F),-1,-1,2,"_hall1D_draw=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_TH2F),-1,-1,2,"_hall2D=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_string),-1,-1,2,"_title=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_string),-1,-1,2,"_titleX=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_string),-1,-1,2,"_titleY=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"_is1D=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"_is2D=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"_systHistosGroups=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_string),-1,-1,2,"_currentSystGroup=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR),G__defined_typename("map<std::string,TH2F*>"),-1,2,"_h1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR),G__defined_typename("map<std::string,TH2F*>"),-1,2,"_h1w=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR),G__defined_typename("map<std::string,TH2F*>"),-1,2,"_h2=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarHistoStack_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncHistoStack(void) {
   /* HistoStack */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__HistoStack_DictLN_HistoStack));
   G__memfunc_setup("HistoStack",1021,G__HistoStack_Dict_537_0_1, 105, G__get_linked_tagnum(&G__HistoStack_DictLN_HistoStack), -1, 0, 3, 1, 1, 0, 
"u 'string' - 11 - title u 'string' - 11 - titleX "
"u 'string' - 11 - titleY", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Is1D",305,G__HistoStack_Dict_537_0_2, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Is2D",306,G__HistoStack_Dict_537_0_3, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Add",265,G__HistoStack_Dict_537_0_4, 121, -1, -1, 0, 6, 1, 1, 0, 
"U 'TH1F' - 0 - h1 i - - 0 - lc "
"i - - 0 - lw i - - 0 - fc "
"i - - 0 - fs u 'string' - 11 - leg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Add",265,G__HistoStack_Dict_537_0_5, 121, -1, -1, 0, 4, 1, 1, 0, 
"U 'TH2F' - 0 - h2 i - - 0 - fc "
"i - - 0 - lc u 'string' - 11 '\"\"' leg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Draw",398,G__HistoStack_Dict_537_0_6, 121, -1, -1, 0, 8, 1, 1, 0, 
"i - - 0 - lc i - - 0 - lw "
"i - - 0 - fc i - - 0 - fs "
"u 'string' - 11 '\"\"' root_opt u 'string' - 11 '\"\"' opt "
"u 'string' - 11 '\"\"' leg_opt i - - 0 '0' mode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Draw",398,G__HistoStack_Dict_537_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 11 '\"\"' root_opt u 'string' - 11 '\"\"' opt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTotal",816,G__HistoStack_Dict_537_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH1F' - 0 - h1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTotal",816,G__HistoStack_Dict_537_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH2F' - 0 - h2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTotal1D",921,G__HistoStack_Dict_537_0_10, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTotalStat1D",1333,G__HistoStack_Dict_537_0_11, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTotalSyst1D",1356,G__HistoStack_Dict_537_0_12, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTotal2D",922,G__HistoStack_Dict_537_0_13, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH2F), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTotal",781,G__HistoStack_Dict_537_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TH1F' - 0 - h1 U 'TH1F' - 0 '0' hsyst", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddSystHistos",1334,G__HistoStack_Dict_537_0_15, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TH2F' - 0 - h1 U 'TH2F' - 0 - h2 "
"U 'TH2F' - 0 - h1w", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSystHistos",1357,G__HistoStack_Dict_537_0_16, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'string' - 11 - group U 'TH2F' - 1 - h1 "
"U 'TH2F' - 1 - h2 U 'TH2F' - 1 - h1w", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddSystHistosGroup",1859,G__HistoStack_Dict_537_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - group", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCurrentSystGroup",1999,G__HistoStack_Dict_537_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - group", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCurrentSystGroup",1987,G__HistoStack_Dict_537_0_19, 117, G__get_linked_tagnum(&G__HistoStack_DictLN_string), -1, 1, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSystHistosGroups",1997,G__HistoStack_Dict_537_0_20, 117, G__get_linked_tagnum(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR), G__defined_typename("vector<std::string>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTotal",781,G__HistoStack_Dict_537_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH2F' - 0 - h2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillLegend",982,G__HistoStack_Dict_537_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TLegend' - 0 - leg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHisto1D",924,G__HistoStack_Dict_537_0_23, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - title", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHisto1D",924,G__HistoStack_Dict_537_0_24, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH1F), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHisto2D",925,G__HistoStack_Dict_537_0_25, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH2F), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - title", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHisto2D",925,G__HistoStack_Dict_537_0_26, 85, G__get_linked_tagnum(&G__HistoStack_DictLN_TH2F), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__HistoStack_Dict_537_0_27, 121, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NormalizeByArea",1509,G__HistoStack_Dict_537_0_28, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 11 - uopt d - - 0 '1' area", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResetDrawHistos",1547,G__HistoStack_Dict_537_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMaximum",1022,G__HistoStack_Dict_537_0_30, 100, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"\"' opt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMaximumWithError",1956,G__HistoStack_Dict_537_0_31, 100, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"\"' opt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMaximum",1034,G__HistoStack_Dict_537_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMinimum",1032,G__HistoStack_Dict_537_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - min", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("HistoStack", 1021, G__HistoStack_Dict_537_0_34, (int) ('i'), G__get_linked_tagnum(&G__HistoStack_DictLN_HistoStack), -1, 0, 1, 1, 1, 0, "u 'HistoStack' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~HistoStack", 1147, G__HistoStack_Dict_537_0_35, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__HistoStack_Dict_537_0_36, (int) ('u'), G__get_linked_tagnum(&G__HistoStack_DictLN_HistoStack), -1, 1, 1, 1, 1, 0, "u 'HistoStack' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncHistoStack_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalHistoStack_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcHistoStack_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__HistoStack_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__HistoStack_DictLN_THStack = { "THStack" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_TLegend = { "TLegend" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_HistoStack = { "HistoStack" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR = { "vector<TH1F*,allocator<TH1F*> >" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1F*,allocator<TH1F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR = { "vector<TH2F*,allocator<TH2F*> >" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2F*,allocator<TH2F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR = { "map<string,TH2F*,less<string>,allocator<pair<const string,TH2F*> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableHistoStack_Dict() {
  G__HistoStack_DictLN_string.tagnum = -1 ;
  G__HistoStack_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__HistoStack_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HistoStack_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__HistoStack_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HistoStack_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__HistoStack_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__HistoStack_DictLN_TH1F.tagnum = -1 ;
  G__HistoStack_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__HistoStack_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__HistoStack_DictLN_TH2F.tagnum = -1 ;
  G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__HistoStack_DictLN_THStack.tagnum = -1 ;
  G__HistoStack_DictLN_TLegend.tagnum = -1 ;
  G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__HistoStack_DictLN_HistoStack.tagnum = -1 ;
  G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__HistoStack_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR.tagnum = -1 ;
  G__HistoStack_DictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR.tagnum = -1 ;
  G__HistoStack_DictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableHistoStack_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_string);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_TH2F);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_THStack);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_TLegend);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_HistoStack),sizeof(HistoStack),-1,295936,(char*)NULL,G__setup_memvarHistoStack,G__setup_memfuncHistoStack);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__HistoStack_DictLN_maplEstringcOTH2FmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH2FmUgRsPgRsPgR);
}
extern "C" void G__cpp_setupHistoStack_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupHistoStack_Dict()");
  G__set_cpp_environmentHistoStack_Dict();
  G__cpp_setup_tagtableHistoStack_Dict();

  G__cpp_setup_inheritanceHistoStack_Dict();

  G__cpp_setup_typetableHistoStack_Dict();

  G__cpp_setup_memvarHistoStack_Dict();

  G__cpp_setup_memfuncHistoStack_Dict();
  G__cpp_setup_globalHistoStack_Dict();
  G__cpp_setup_funcHistoStack_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncHistoStack_Dict();
  return;
}
class G__cpp_setup_initHistoStack_Dict {
  public:
    G__cpp_setup_initHistoStack_Dict() { G__add_setup_func("HistoStack_Dict",(G__incsetup)(&G__cpp_setupHistoStack_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initHistoStack_Dict() { G__remove_setup_func("HistoStack_Dict"); }
};
G__cpp_setup_initHistoStack_Dict G__cpp_setup_initializerHistoStack_Dict;

