/********************************************************************
* dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict();
extern void G__cpp_setup_inheritancedict();
extern void G__cpp_setup_typetabledict();
extern void G__cpp_setup_memvardict();
extern void G__cpp_setup_globaldict();
extern void G__cpp_setup_memfuncdict();
extern void G__cpp_setup_funcdict();
extern void G__set_cpp_environmentdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TND280UpEvent.hh"
#include "TND280UpHit.hh"
#include "TND280UpRecoEvent.hh"
#include "TND280UpRecoTrack.hh"
#include "TND280UpTrack.hh"
#include "TND280UpTrackPoint.hh"
#include "TND280UpVertex.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictLN_TClass;
extern G__linked_taginfo G__dictLN_TBuffer;
extern G__linked_taginfo G__dictLN_TMemberInspector;
extern G__linked_taginfo G__dictLN_TObject;
extern G__linked_taginfo G__dictLN_string;
extern G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_TList;
extern G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__dictLN_TVector3;
extern G__linked_taginfo G__dictLN_TND280UpTrackPoint;
extern G__linked_taginfo G__dictLN_TND280UpTrack;
extern G__linked_taginfo G__dictLN_TND280UpVertex;
extern G__linked_taginfo G__dictLN_TND280UpHit;
extern G__linked_taginfo G__dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_TND280UpEvent;
extern G__linked_taginfo G__dictLN_TH2F;
extern G__linked_taginfo G__dictLN_TND280UpRecoTrack;
extern G__linked_taginfo G__dictLN_TND280UpRecoEvent;
extern G__linked_taginfo G__dictLN_vectorlETND280UpVertexcOallocatorlETND280UpVertexgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpVertexcOallocatorlETND280UpVertexgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETND280UpVertexcOallocatorlETND280UpVertexgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpTrackcOallocatorlETND280UpTrackgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpTrackcOallocatorlETND280UpTrackgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETND280UpTrackcOallocatorlETND280UpTrackgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpTrackPointcOallocatorlETND280UpTrackPointgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpTrackPointcOallocatorlETND280UpTrackPointgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETND280UpTrackPointcOallocatorlETND280UpTrackPointgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpHitcOallocatorlETND280UpHitgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpHitcOallocatorlETND280UpHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETND280UpHitcOallocatorlETND280UpHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpRecoTrackcOallocatorlETND280UpRecoTrackgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlETND280UpRecoTrackcOallocatorlETND280UpRecoTrackgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETND280UpRecoTrackcOallocatorlETND280UpRecoTrackgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<TND280UpVertex,allocator<TND280UpVertex> > G__vectorlETND280UpVertexcOallocatorlETND280UpVertexgRsPgR;
typedef vector<TND280UpTrack,allocator<TND280UpTrack> > G__vectorlETND280UpTrackcOallocatorlETND280UpTrackgRsPgR;
typedef vector<TND280UpTrackPoint,allocator<TND280UpTrackPoint> > G__vectorlETND280UpTrackPointcOallocatorlETND280UpTrackPointgRsPgR;
typedef vector<TND280UpHit,allocator<TND280UpHit> > G__vectorlETND280UpHitcOallocatorlETND280UpHitgRsPgR;
typedef vector<TND280UpRecoTrack,allocator<TND280UpRecoTrack> > G__vectorlETND280UpRecoTrackcOallocatorlETND280UpRecoTrackgRsPgR;
