/********************************************************************
* ../dict/CategoryClasses_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/CategoryClasses_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCategoryClasses_Dict();
extern void G__cpp_setup_inheritanceCategoryClasses_Dict();
extern void G__cpp_setup_typetableCategoryClasses_Dict();
extern void G__cpp_setup_memvarCategoryClasses_Dict();
extern void G__cpp_setup_globalCategoryClasses_Dict();
extern void G__cpp_setup_memfuncCategoryClasses_Dict();
extern void G__cpp_setup_funcCategoryClasses_Dict();
extern void G__set_cpp_environmentCategoryClasses_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/CategoryClasses.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CategoryClasses_DictLN_TClass;
extern G__linked_taginfo G__CategoryClasses_DictLN_TBuffer;
extern G__linked_taginfo G__CategoryClasses_DictLN_TMemberInspector;
extern G__linked_taginfo G__CategoryClasses_DictLN_TObject;
extern G__linked_taginfo G__CategoryClasses_DictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__CategoryClasses_DictLN_string;
extern G__linked_taginfo G__CategoryClasses_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CategoryClasses_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CategoryClasses_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CategoryClasses_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CategoryClasses_DictLN_TrackTypeDefinition;
extern G__linked_taginfo G__CategoryClasses_DictLN_TrackCategoryDefinition;
extern G__linked_taginfo G__CategoryClasses_DictLN_vectorlETrackTypeDefinitioncOallocatorlETrackTypeDefinitiongRsPgR;
extern G__linked_taginfo G__CategoryClasses_DictLN_reverse_iteratorlEvectorlETrackTypeDefinitioncOallocatorlETrackTypeDefinitiongRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
