/********************************************************************
* ../dict/CategoryManager_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/CategoryManager_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCategoryManager_Dict();
extern void G__cpp_setup_inheritanceCategoryManager_Dict();
extern void G__cpp_setup_typetableCategoryManager_Dict();
extern void G__cpp_setup_memvarCategoryManager_Dict();
extern void G__cpp_setup_globalCategoryManager_Dict();
extern void G__cpp_setup_memfuncCategoryManager_Dict();
extern void G__cpp_setup_funcCategoryManager_Dict();
extern void G__set_cpp_environmentCategoryManager_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/CategoryManager.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CategoryManager_DictLN_string;
extern G__linked_taginfo G__CategoryManager_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CategoryManager_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CategoryManager_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CategoryManager_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CategoryManager_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CategoryManager_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__CategoryManager_DictLN_HLClonesArray;
extern G__linked_taginfo G__CategoryManager_DictLN_TrackCategoryDefinition;
extern G__linked_taginfo G__CategoryManager_DictLN_vectorlETrackTypeDefinitioncOallocatorlETrackTypeDefinitiongRsPgR;
extern G__linked_taginfo G__CategoryManager_DictLN_reverse_iteratorlEvectorlETrackTypeDefinitioncOallocatorlETrackTypeDefinitiongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CategoryManager_DictLN_CategoryManager;
extern G__linked_taginfo G__CategoryManager_DictLN_maplEstringcOTrackCategoryDefinitionmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTrackCategoryDefinitionmUgRsPgRsPgR;

/* STUB derived class for protected member access */
