/********************************************************************
* ../dict/CorrectionBase_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/CorrectionBase_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCorrectionBase_Dict();
extern void G__cpp_setup_inheritanceCorrectionBase_Dict();
extern void G__cpp_setup_typetableCorrectionBase_Dict();
extern void G__cpp_setup_memvarCorrectionBase_Dict();
extern void G__cpp_setup_globalCorrectionBase_Dict();
extern void G__cpp_setup_memfuncCorrectionBase_Dict();
extern void G__cpp_setup_funcCorrectionBase_Dict();
extern void G__set_cpp_environmentCorrectionBase_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/CorrectionBase.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CorrectionBase_DictLN_TClass;
extern G__linked_taginfo G__CorrectionBase_DictLN_TBuffer;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMemberInspector;
extern G__linked_taginfo G__CorrectionBase_DictLN_TObject;
extern G__linked_taginfo G__CorrectionBase_DictLN_string;
extern G__linked_taginfo G__CorrectionBase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_AnaSpillC;
extern G__linked_taginfo G__CorrectionBase_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CorrectionBase_DictLN_CorrectionBase;

/* STUB derived class for protected member access */
