/********************************************************************
* ../dict/VersionManager_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/VersionManager_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableVersionManager_Dict();
extern void G__cpp_setup_inheritanceVersionManager_Dict();
extern void G__cpp_setup_typetableVersionManager_Dict();
extern void G__cpp_setup_memvarVersionManager_Dict();
extern void G__cpp_setup_globalVersionManager_Dict();
extern void G__cpp_setup_memfuncVersionManager_Dict();
extern void G__cpp_setup_funcVersionManager_Dict();
extern void G__set_cpp_environmentVersionManager_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/VersionManager.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__VersionManager_DictLN_TClass;
extern G__linked_taginfo G__VersionManager_DictLN_TBuffer;
extern G__linked_taginfo G__VersionManager_DictLN_TMemberInspector;
extern G__linked_taginfo G__VersionManager_DictLN_TObject;
extern G__linked_taginfo G__VersionManager_DictLN_string;
extern G__linked_taginfo G__VersionManager_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__VersionManager_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VersionManager_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__VersionManager_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VersionManager_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__VersionManager_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__VersionManager_DictLN_PackageVersion;
extern G__linked_taginfo G__VersionManager_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__VersionManager_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VersionManager_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__VersionManager_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VersionManager_DictLN_vectorlEPackageVersionmUcOallocatorlEPackageVersionmUgRsPgR;
extern G__linked_taginfo G__VersionManager_DictLN_reverse_iteratorlEvectorlEPackageVersionmUcOallocatorlEPackageVersionmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
