/********************************************************************
* ../dict/TND280UpEvent_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/TND280UpEvent_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTND280UpEvent_Dict();
extern void G__cpp_setup_inheritanceTND280UpEvent_Dict();
extern void G__cpp_setup_typetableTND280UpEvent_Dict();
extern void G__cpp_setup_memvarTND280UpEvent_Dict();
extern void G__cpp_setup_globalTND280UpEvent_Dict();
extern void G__cpp_setup_memfuncTND280UpEvent_Dict();
extern void G__cpp_setup_funcTND280UpEvent_Dict();
extern void G__set_cpp_environmentTND280UpEvent_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/TND280UpEvent.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TND280UpEvent_DictLN_TClass;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TBuffer;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMemberInspector;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TObject;
extern G__linked_taginfo G__TND280UpEvent_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TList;
extern G__linked_taginfo G__TND280UpEvent_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TND280UpTrack;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TND280UpVertex;
extern G__linked_taginfo G__TND280UpEvent_DictLN_TND280UpEvent;
extern G__linked_taginfo G__TND280UpEvent_DictLN_vectorlETND280UpEventcOallocatorlETND280UpEventgRsPgR;
extern G__linked_taginfo G__TND280UpEvent_DictLN_vectorlETND280UpEventcOallocatorlETND280UpEventgRsPgRcLcLiterator;
extern G__linked_taginfo G__TND280UpEvent_DictLN_reverse_iteratorlEvectorlETND280UpEventcOallocatorlETND280UpEventgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<TND280UpEvent,allocator<TND280UpEvent> > G__vectorlETND280UpEventcOallocatorlETND280UpEventgRsPgR;
