/********************************************************************
* ../dict/DataSample_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/DataSample_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataSample_Dict();
extern void G__cpp_setup_inheritanceDataSample_Dict();
extern void G__cpp_setup_typetableDataSample_Dict();
extern void G__cpp_setup_memvarDataSample_Dict();
extern void G__cpp_setup_globalDataSample_Dict();
extern void G__cpp_setup_memfuncDataSample_Dict();
extern void G__cpp_setup_funcDataSample_Dict();
extern void G__set_cpp_environmentDataSample_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/DataSample.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataSample_DictLN_string;
extern G__linked_taginfo G__DataSample_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataSample_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataSample_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataSample_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataSample_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DataSample_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DataSample_DictLN_TreeManager;
extern G__linked_taginfo G__DataSample_DictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR;
extern G__linked_taginfo G__DataSample_DictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataSample_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__DataSample_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DataSample_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DataSample_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DataSample_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR;
extern G__linked_taginfo G__DataSample_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataSample_DictLN_Header;
extern G__linked_taginfo G__DataSample_DictLN_DataSample;

/* STUB derived class for protected member access */
