/********************************************************************
* ../dict/Header_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/Header_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHeader_Dict();
extern void G__cpp_setup_inheritanceHeader_Dict();
extern void G__cpp_setup_typetableHeader_Dict();
extern void G__cpp_setup_memvarHeader_Dict();
extern void G__cpp_setup_globalHeader_Dict();
extern void G__cpp_setup_memfuncHeader_Dict();
extern void G__cpp_setup_funcHeader_Dict();
extern void G__set_cpp_environmentHeader_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/Header.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Header_DictLN_string;
extern G__linked_taginfo G__Header_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Header_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Header_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Header_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Header_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Header_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Header_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Header_DictLN_AnaSpillC;
extern G__linked_taginfo G__Header_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR;
extern G__linked_taginfo G__Header_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Header_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Header_DictLN_TTree;
extern G__linked_taginfo G__Header_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__Header_DictLN_Header;

/* STUB derived class for protected member access */
