/********************************************************************
* ../dict/HLClonesArray_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/HLClonesArray_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHLClonesArray_Dict();
extern void G__cpp_setup_inheritanceHLClonesArray_Dict();
extern void G__cpp_setup_typetableHLClonesArray_Dict();
extern void G__cpp_setup_memvarHLClonesArray_Dict();
extern void G__cpp_setup_globalHLClonesArray_Dict();
extern void G__cpp_setup_memfuncHLClonesArray_Dict();
extern void G__cpp_setup_funcHLClonesArray_Dict();
extern void G__set_cpp_environmentHLClonesArray_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/HLClonesArray.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HLClonesArray_DictLN_string;
extern G__linked_taginfo G__HLClonesArray_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HLClonesArray_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HLClonesArray_DictLN_TClonesArray;
extern G__linked_taginfo G__HLClonesArray_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HLClonesArray_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HLClonesArray_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HLClonesArray_DictLN_TTree;
extern G__linked_taginfo G__HLClonesArray_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__HLClonesArray_DictLN_TChain;
extern G__linked_taginfo G__HLClonesArray_DictLN_HLClonesArray;

/* STUB derived class for protected member access */
