/********************************************************************
* ../dict/StepBase_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/StepBase_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableStepBase_Dict();
extern void G__cpp_setup_inheritanceStepBase_Dict();
extern void G__cpp_setup_typetableStepBase_Dict();
extern void G__cpp_setup_memvarStepBase_Dict();
extern void G__cpp_setup_globalStepBase_Dict();
extern void G__cpp_setup_memfuncStepBase_Dict();
extern void G__cpp_setup_funcStepBase_Dict();
extern void G__set_cpp_environmentStepBase_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/StepBase.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__StepBase_DictLN_TClass;
extern G__linked_taginfo G__StepBase_DictLN_TBuffer;
extern G__linked_taginfo G__StepBase_DictLN_TMemberInspector;
extern G__linked_taginfo G__StepBase_DictLN_TObject;
extern G__linked_taginfo G__StepBase_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__StepBase_DictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__StepBase_DictLN_string;
extern G__linked_taginfo G__StepBase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__StepBase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StepBase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__StepBase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StepBase_DictLN_ToyBoxB;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__StepBase_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__StepBase_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__StepBase_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR;
extern G__linked_taginfo G__StepBase_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StepBase_DictLN_AnaEventC;
extern G__linked_taginfo G__StepBase_DictLN_StepBase;
extern G__linked_taginfo G__StepBase_DictLN_StepBasecLcLTypeEnum;
extern G__linked_taginfo G__StepBase_DictLN_StepBasecLcLBranchStatus;
extern G__linked_taginfo G__StepBase_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR;
extern G__linked_taginfo G__StepBase_DictLN_reverse_iteratorlEvectorlEStepBasemUcOallocatorlEStepBasemUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
