/********************************************************************
* ../dict/SystematicBase_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../dict/SystematicBase_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSystematicBase_Dict();
extern void G__cpp_setup_inheritanceSystematicBase_Dict();
extern void G__cpp_setup_typetableSystematicBase_Dict();
extern void G__cpp_setup_memvarSystematicBase_Dict();
extern void G__cpp_setup_globalSystematicBase_Dict();
extern void G__cpp_setup_memfuncSystematicBase_Dict();
extern void G__cpp_setup_funcSystematicBase_Dict();
extern void G__set_cpp_environmentSystematicBase_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/SystematicBase.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SystematicBase_DictLN_TClass;
extern G__linked_taginfo G__SystematicBase_DictLN_TBuffer;
extern G__linked_taginfo G__SystematicBase_DictLN_TMemberInspector;
extern G__linked_taginfo G__SystematicBase_DictLN_TObject;
extern G__linked_taginfo G__SystematicBase_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_string;
extern G__linked_taginfo G__SystematicBase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SystematicBase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SystematicBase_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SystematicBase_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__SystematicBase_DictLN_vectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_reverse_iteratorlEvectorlEAnaBunchCmUcOallocatorlEAnaBunchCmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SystematicBase_DictLN_AnaEventC;
extern G__linked_taginfo G__SystematicBase_DictLN_vectorlEStepBasemUcOallocatorlEStepBasemUgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_reverse_iteratorlEvectorlEStepBasemUcOallocatorlEStepBasemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SystematicBase_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SystematicBase_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SystematicBase_DictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SystematicBase_DictLN_SystBoxB;
extern G__linked_taginfo G__SystematicBase_DictLN_setlEAnaRecObjectCmUcOlesslEAnaRecObjectCmUgRcOallocatorlEAnaRecObjectCmUgRsPgR;
extern G__linked_taginfo G__SystematicBase_DictLN_SystematicBase;
extern G__linked_taginfo G__SystematicBase_DictLN_SystematicBasecLcLTypeEnum;
extern G__linked_taginfo G__SystematicBase_DictLN_SystematicBasecLcLPDFEnum;

/* STUB derived class for protected member access */
