#! /bin/csh -f

set code_dir = /sps/t2k/mlamoure/dev/Upgrade/t2k-nd280-upgrade/highlandUP/numuCC4piAnalysis/v0r0
set par_dir = ${code_dir}/output/jobs/parameters
set log_dir = ${code_dir}/output/jobs/logs
set job_dir = ${code_dir}/output/jobs/jobs
set out_dir = ${code_dir}/output/jobs/files

set launcher = launchJobs
set conc = ${out_dir}/concatenate

# clear all the directories
rm -rf ${par_dir}/*
rm -rf ${log_dir}/*
rm -rf ${job_dir}/*
rm -f $launcher
touch $launcher
rm -f ${conc}
touch ${conc}
