#!/bin/bash

source /nfs/neutrinos/cjesus/T2K/work/Run_At_Start_T2K.sh
source /software/neutrinos/t2k-nd280-upgrade/highlandUP/numuCC4piAnalysis/v0r0/cmt/setup.sh

#set upgrade_dir = /software/neutrinos/t2k-nd280-upgrade
#set code_dir = ${upgrade_dir}/highlandUP/numuCC4piAnalysis/v0r0
#set job_dir = ${upgrade_dir}/highlandUP/numuCC4piAnalysis/v0r0/output/jobs
#cd ${job_dir}

cd /software/neutrinos/t2k-nd280-upgrade/highlandUP/numuCC4piAnalysis/v0r0/output/jobs

rm -f $2
#${code_dir}/Linux-x86_64/RunNumuCC4piAnalysis.exe -p $1 -o $2 $3
/software/neutrinos/t2k-nd280-upgrade/highlandUP/numuCC4piAnalysis/v0r0/Linux-x86_64/RunNumuCC4piAnalysis.exe -p $1 -o $2 $3  